name: CustomChestCommand
main: com.yourname.customchestcommand.Main
version: 1.0
api-version: 1.21
commands:
  chest:
    description: 특정 좌표에 아이템이 담긴 상자를 소환
    usage: /chest <x> <y> <z> <item> <amount>
    permission: chestcommand.use
permissions:
  chestcommand.use:
    default: true
